apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://rpi-control:30900
      basicAuth: false
      isDefault: true
      version: 1
