{
 "title": "k3s cluster",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Temperature by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "__auto" }
   ]
  }
 ]
}
{
 "title": "RuuviTag data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Room temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ruuvi_temperature_c", "legendFormat": "{{ location }}" }
   ]
  },
  {
   "title": "Humidity %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ruuvi_humidity_percent * 100", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ruuvi_pressure_hpa", "legendFormat": "{{ location }}" }
   ]
  },
  {
   "title": "Battery level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ruuvi_battery_v", "legendFormat": "{{location}}" }
   ]
  }
 ]
}