apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 31300
      port: 3000
      protocol: TCP
      targetPort: web
  selector:
    app: grafana
