apiVersion: apps/v1
kind: Deployment
metadata:
  name: riot-merch-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot-merch-scraper
  template:
    metadata:
      labels:
        app: riot-merch-scraper
    spec:
      containers:
        - name: riot-merch-scraper
          image: rpi-control:31000/riot-merch-scraper
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: riot-merch-scraper-config
        - name: db
          image: postgres
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgresql-config
          command:
            ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: postgresql-config
              mountPath: /etc/postgresql
      initContainers:
        - name: initdb
          image: postgres
          command: ["initdb", "-D", "/var/lib/postgresql/data"]
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: etc-passwd
              mountPath: /etc/passwd
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      restartPolicy: Always
      volumes:
        - name: etc-passwd
          hostPath:
            path: /etc/passwd
        - name: postgresql-data
          hostPath:
            path: /home/postgres/data
        - name: postgresql-config
          configMap:
            name: postgresql-config
