apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 31000
      port: 5000
      protocol: TCP
      targetPort: web
  selector:
    app: docker-registry
