apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pv
  labels:
    name: docker-pv
spec:
  resources:
    requests:
      storage: 90Gi
  accessModes:
    - ReadWriteOnce # required
  storageClassName: local-path
