apiVersion: v1
kind: Service
metadata:
  name: riot-merch-info
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30999
      port: 9999
      protocol: TCP
      targetPort: flask
  selector:
    app: riot-merch-info
