---
- name: Apply nginx ingress deployment manifest
  ansible.builtin.command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml"
  register: result

- debug:
    msg: "{{ result }}"
