apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
        - name: weather-station
          image: rpi-control:31000/alpine-ruuvi:arm
          command: ["python3", "main.py"]
          ports:
            - name: metrics
              containerPort: 8000
          volumeMounts:
            - name: dbus-volume
              mountPath: /var/run/dbus
      volumes:
        - name: dbus-volume
          hostPath:
            path: /var/run/dbus
