apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    alper: test
spec:
  containers:
    - name: prometheus
      volumeMounts:
        - name: prom-data
          mountPath: /prometheus
  retention: 3650d
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  volumes:
    - name: prom-data
      persistentVolumeClaim:
        claimName: prom-pv
