apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pv
  labels:
    name: prom-pv
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce # required
  storageClassName: local-path
